version: '3'
services:
    mysql:
      image: mysql
      environment:
        - MYSQL_USER=root
        - MYSQL_DATABASE=spring_blog_prod
        - MYSQL_ROOT_PASSWORD=Aliyun18@Better
    webapp:
      image: java:8
      depends_on:
        - mysql
        - redis
      volumes:
        - ./application-prod.yml:/app/application-prod.yml
        - ./build/libs/SpringBlog-0.0.1-SNAPSHOT.jar:/app/app.jar
      ports:
        - "80:8080"
#      command: "java -jar /app/app.jar --spring.profiles.active=prod --spring.config.location=/app/application-prod.yml"
      command: "java -jar /app/app.jar --spring.profiles.active=prod"

    redis:
      image: redis
