spring:
    profiles:
        active: dev

    thymeleaf:
        cache: false

    devtools:
        restart:
            enabled: true
            exclude: static/**,templates/**

    jade4j:
        caching: false

    jpa:
        show-sql: true

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://127.0.0.1/spring_blog_prod?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456

        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

logging:
  level:
    org.springframework.web: ERROR
    com.raysmond.blog: DEBUG
